### ISSUE TITLE
`collab_pls` does not iteratively update the baseline

### ISSUE THREAD

**Issue by kelleyjbrady** [derb12/pybaselines#21]
### Description
`collab_pls` does not iteratively update the baseline. Also, the docstring for `method_kwargs` is from `v0.7`, right? The `**` does not apply anymore since `method_kwargs` should be a `dict`. 

### Your Setup

3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0]
0.8.0

### Example Code

See my comments below. To my understanding, setting `method_kwargs['tol'] = np.inf` leads to Whitaker optimization terminating after one iteration, regardless of the value of the loss function because (for example in aspls line 730):
```python
if calc_difference < tol:
            break
```
will always lead to early stopping because anything is `< np.inf`. It seems to me that removing the `method_kwargs['tol'] = np.inf` will lead to proper optimization for the component spectra used in the collab.

```python
def collab_pls(data, average_dataset=True, method='asls', method_kwargs=None, **kwargs):
    """
    Collaborative Penalized Least Squares (collab-PLS).

    Averages the data or the fit weights for an entire dataset to get more
    optimal results. Uses any Whittaker-smoothing-based or weighted spline algorithm.

    Parameters
    ----------
    data : array-like, shape (M, N)
        An array with shape (M, N) where M is the number of entries in
        the dataset and N is the number of data points in each entry.
    average_dataset : bool, optional
        If True (default) will average the dataset before fitting to get the
        weighting. If False, will fit each individual entry in the dataset and
        then average the weights to get the weighting for the dataset.
    method : str, optional
        A string indicating the Whittaker-smoothing-based or weighted spline method to
        use for fitting the baseline. Default is 'asls'.
    **method_kwargs
        Keyword arguments to pass to the selected `method` function.

    Returns
    -------
    baselines : np.ndarray, shape (M, N)
        An array of all of the baselines.
    params : dict
        A dictionary with the following items:

        * 'average_weights': numpy.ndarray, shape (N,)
            The weight array used to fit all of the baselines.

        Additional items depend on the output of the selected method. Every
        other key will have a list of values, with each item corresponding to a
        fit.

    References
    ----------
    Chen, L., et al. Collaborative Penalized Least Squares for Background
    Correction of Multiple Raman Spectra. Journal of Analytical Methods
    in Chemistry, 2018, 2018.

    """
    dataset, fit_func, _, method_kws = _setup_optimizer(
        data, method, (whittaker, morphological, classification, spline), method_kwargs,
        True, **kwargs
    )
    if dataset.ndim < 2:
        raise ValueError((
            'the input data must have a shape of (number of measurements, number of points), '
            f'but instead has a shape of {dataset.shape}'
        ))
    if average_dataset:
        _, fit_params = fit_func(np.mean(dataset.T, 1), **method_kws)
        method_kws['weights'] = fit_params['weights']
    else:
        weights = np.empty_like(dataset)
        for i, entry in enumerate(dataset):
            _, fit_params = fit_func(entry, **method_kws)
            weights[i] = fit_params['weights']
        method_kws['weights'] = np.mean(weights.T, 1)
        
    # Why is `tol` being set to `np.inf`?
    # With `tol=np.inf`, the Whitaker algorithms only go though one optimization iteration
    # This can be verfied by inspecting the `params` output of this function, where it . . .
    # . . . can be seen that after fitting with `collab_pls` the `tol_history` is a `list` of `np.array`'s . . .
    # . . . where the list has length n-spectrum-used-to-colab and each array is n-optimization-iters long. 
    # When `colab_pls` is used each of the arrays in the list are 1 entry long.
    #  In contrast the `params` portion of the output of non-colab `aspls`, for example, will contain a `np.array` of decreasing loss . . .
    # . . . values. 
    method_kws['tol'] = np.inf
    baselines = np.empty(dataset.shape)
    params = {'average_weights': method_kws['weights']}
    method = method.lower()
    if method == 'fabc':
        # have to handle differently since weights for fabc is the mask for
        # classification rather than weights for fitting
        fit_func = _whittaker_smooth
        for key in list(method_kws.keys()):
            if key not in {'weights', 'lam', 'diff_order'}:
                method_kws.pop(key)

    for i, entry in enumerate(dataset):
        baselines[i], param = fit_func(entry, **method_kws)
        if method == 'fabc':
            param = {'weights': param}
        for key, value in param.items():
            if key in params:
                params[key].append(value)
            else:
                params[key] = [value]

    return baselines, params


```

### Error Message
No errors
```

**Comment by derb12** [comment]
The `collab_pls` algorithm is based on the idea that using one set of averaged weights for a dataset of similar spectra is better than using individual weights for each individual spectrum. It is a two step process:

a) Calculate the weights for the dataset (the code above your added comments); this is done by either fitting each individual spectrum and averaging the final weights, or by averaging the dataset, fitting, and using the final weights. This step will iteratively calculate the weights like you expected.
b) Use the fixed weights from step (a) and fit each individual spectrum. The tolerance for this step is set to `inf` so that only a single iteration is completed. Otherwise, the weights would be updated, which would ultimately give the same results as if you were to just fit each individual spectrum using the specified fitting function.

As far as the output parameters are concerned, I think `collab_pls`'s parameters are not very helpful since they are from step (b), where only a single iteration is completed. I could maybe add an additional item in the output params that contains the parameters from step (a) as well, which would be more useful and more closely match what you expected.

The `aspls` method is actually tricky to use with `collab_pls`, since it has the additional `alpha` array, which needs to be iteratively updated. If you're getting bad results, I would guess that is the reason. I think the best course of action would be to do a similar approach as for the weights, where one `alpha` parameter is calculated for the dataset and used for each individual spectrum. I will test that out and see if it gives good results. If so, I'll add it in. Thanks for bringing that to my attention.

Also, thanks for pointing out the needed change in the docstring. I missed that for `adaptive_minmax` too.

**Comment by kelleyjbrady** [comment]
I see, yeah it was the fact that `alpha` arrays were  filled with `1` that led me to look at the number of iterations being done, but I didn't quite grasp how `aspls` would behave differently than the other `whittaker` methods. It could be helpful to put a comment above the second `fit_func` to remind people that when the weight param for an estimator is not `None`, the weights in `method_kwargs` are used during optimization, but that the second round of optimization initiated at the second `fit_func` call stops before any updates to the input weights due to `tol=np.inf` (yes, I am restating what you said above 👍 ). Alternatively,  the second `fit_func` could have a different function name that makes it more clear that the purpose of the second call is to update the weights rather than fit the func, if you will. I think that is what confused me at first.

**Comment by kelleyjbrady** [comment]
I wanted to drop back by to say that I re-read the colabPLS paper, and the authors actually say that one of the advantages of the colab method is greatly reduced sensitivity to the `lam` parameter. As `alpha` is just a mask on `lam`, I would thus anticipate that implementing `alpha` sharing will probably not change the results too much. Cheers!

**Comment by derb12** [comment]
My quick testing showed just a small change when implementing the `alpha` sharing, so I think your intuition was correct. I still think implementing a special case for `aspls` makes sense, even if it doesn't have much effect, since otherwise the `alpha` array will just be ones or rely on the user inputting the desired array. I made the change to `collab_pls` on the development branch. If you want, you can try it out by doing:

```shell
pip install git+https://github.com/derb12/pybaselines.git@development
```

although you will have to manually uninstall your current installation of pybaselines first.

I think adding some comments within the `collab_pls` function would be helpful; I will add it later in the week.

**Comment by derb12** [comment]
I added some comments to `collab_pls` to outline the two separate steps and renamed `fit_func` to `baseline_func` to hopefully clear up the variable's usage. You can see on the development branch. Hopefully that will help others when looking at the code in the future. Thanks for all the helpful suggestions.

**Comment by derb12** [comment]
I wanted to double check with you to make sure that you're satisfied with the above response so that I can close this issue. I'll hopefully merge the changes into the main branch in the next week or two for releasing in version 1.0. Thanks again for the helpful feedback!
