### ISSUE TITLE
Rubberband correction

### ISSUE THREAD

**Issue by abdelq** [derb12/pybaselines#5]
### Description of the problem/new feature

Like in https://stats.stackexchange.com/questions/240679, I can't find a specific paper of origin for the method, but it's not an uncommon one and should probably be included.

### Description of a possible solution or alternative

Here is my version of the implementation:

```python
import numpy as np
from scipy.spatial import ConvexHull

def rb_baseline(x, y):
    v = ConvexHull(np.column_stack((x, y))).vertices
    v = np.roll(v, -v.argmin())
    v = v[:v.argmax() + 1]
    return np.interp(x, x[v], y[v])
```

It is very similar to the one in https://dsp.stackexchange.com/questions/2725, but with some fixes.

**Comment by derb12** [comment]
I considered adding that method when I was first making this library, but I decided against it. Since the method and code are so beautifully simple, any implementation I made would more or less just be copying the code from Stack Exchange, which I don't want to do. In this instance, a reference paper wouldn't help since computing the convex hull is really the only difficult part, and unless I wrote my own method to compute the hull (which would be a waste of time and ultimately inferior to SciPy's anyway), the end result would still be a copy of that Stack Exchange code.

There is a more robust rubberband method patented by Bruker (https://patents.google.com/patent/US7359815B2) that's used in software such as Opus. It basically iteratively adds a convex function to the data to coerce it into a convex shape so that the rubberband method works for even non-convex data (see the figure below). I implemented a version using a negative gaussian with a width of +- 1 sigma as the convex-coercing function, and was pretty happy with the results. However, I also wouldn't be comfortable putting that into the library since it's derived from a patented method.

So, all in all, I'd rather just exclude the rubberband method and point users to that Stack Exchange page if they wanted it.

![image](https://user-images.githubusercontent.com/55961724/120051753-e7160100-bfef-11eb-8058-b8894d5cf21c.png)

**Comment by abdelq** [comment]
> There is a more robust rubberband method patented by Bruker (https://patents.google.com/patent/US7359815B2) that's used in software such as Opus. It basically iteratively adds a convex function to the data to coerce it into a convex shape so that the rubberband method works for even non-convex data (see the figure below).

Interesting! Thanks for sharing.

> So, all in all, I'd rather just exclude the rubberband method and point users to that Stack Exchange page if they wanted it.

Reasonable.
